#!/usr/bin/env python3
r"""Augmented Xi closed-cone limit theorem.

This theorem composes the split augmented Xi-trace inputs:

1. finite augmented pullback identity;
2. compact kernel / trace convergence;
3. repair positivity in the transported augmented trace space.
4. finite PSD cone closure under entrywise limits.

The conclusion is that the full shifted-Xi de Branges kernel belongs to the
closed positive cone generated by augmented KLM pullbacks.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def load(path: str) -> dict:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def status(label: str, ok: bool, reason: str) -> dict:
    return {
        "label": label,
        "closed": ok,
        "status": "closed" if ok else "open",
        "reason": reason,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--finite-pullback-json",
        default="xi_finite_augmented_pullback_identity_theorem.json",
    )
    parser.add_argument(
        "--trace-convergence-json",
        default="xi_augmented_trace_convergence_theorem.json",
    )
    parser.add_argument(
        "--repair-positive-json",
        default="xi_augmented_repair_positive_consequence_theorem.json",
    )
    parser.add_argument(
        "--psd-closure-json",
        default="finite_psd_cone_closure_theorem.json",
    )
    parser.add_argument("--json-out", default="xi_augmented_closed_cone_limit_theorem.json")
    args = parser.parse_args()

    finite = load(args.finite_pullback_json)
    trace = load(args.trace_convergence_json)
    repair = load(args.repair_positive_json)
    psd = load(args.psd_closure_json)

    finite_ok = bool(finite.get("finiteThetaAugmentedPullbackClosed"))
    convergence_ok = bool(
        trace.get("uniformCompactConvergenceClosed")
        and trace.get("closedTraceConvergenceClosed")
    )
    repair_ok = bool(repair.get("continuumAugmentedRepairClosed"))
    psd_ok = bool(psd.get("finitePsdConeClosureClosed"))
    cone_ok = finite_ok and convergence_ok and repair_ok and psd_ok

    finite_status = status(
        "finite positive augmented pullbacks",
        finite_ok,
        (
            "For each finite theta truncation, K_{E,N} is represented by a "
            "KLM pullback plus the augmented nonnegative trace repair."
        ),
    )
    convergence_status = status(
        "compact-open and trace convergence",
        convergence_ok,
        (
            "K_{E,N}->K_E entrywise on finite compact evaluation sets and "
            "R_aug,N->R_aug in the transported graph-dual topology."
        ),
    )
    repair_status = status(
        "nonnegative continuum repair",
        repair_ok,
        (
            "The narrow repair-consequence theorem exports D_aug>=0 on X_aug "
            "and the closed repaired-form conclusion, without importing the "
            "transport proof machinery into this closed-cone layer."
        ),
    )
    cone_status = status(
        "closed positive-cone limit",
        cone_ok,
        (
            "The finite PSD cone closure theorem applies to each finite "
            "evaluation Gram matrix.  Since K_{E,N}->K_E entrywise and the "
            "finite augmented pullbacks are positive after repair, the full "
            "kernel K_E lies in the closed augmented KLM positive cone."
        ),
    )

    data = {
        "theoremName": "augmented Xi closed-cone limit theorem",
        "proofClass": "analytic proof",
        "finitePullbackJson": args.finite_pullback_json,
        "traceConvergenceJson": args.trace_convergence_json,
        "repairPositiveJson": args.repair_positive_json,
        "psdClosureJson": args.psd_closure_json,
        "statuses": {
            "finitePositivePullbackStatus": finite_status,
            "compactTraceConvergenceStatus": convergence_status,
            "nonnegativeRepairStatus": repair_status,
            "finitePsdConeClosureStatus": psd.get("statuses", {}).get(
                "finitePsdConeClosureStatus"
            ),
            "closedPositiveConeStatus": cone_status,
        },
        "closedConeConclusionClosed": cone_ok,
        "hardenedContinuumLiftClosed": cone_ok,
        "entrywiseConvergenceToFullDeBrangesKernel": convergence_ok,
        "continuumAugmentedRepairClosed": repair_ok,
        "proof": [
            "Apply the finite augmented pullback theorem to each Xi_N.",
            "Use compact-open convergence to pass K_{E,N} finite Gram entries to K_E.",
            "Use the narrow continuum repair consequence to keep the augmented repair nonnegative.",
            "Use the finite PSD cone closure theorem under entrywise limits.",
        ],
        "remainingAnalyticGap": None if cone_ok else "One split closed-cone input is open.",
    }

    Path(args.json_out).write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print("Augmented Xi closed-cone limit theorem")
    print(f"  finite pullback: {finite_ok}")
    print(f"  convergence: {convergence_ok}")
    print(f"  repair positivity: {repair_ok}")
    print(f"  finite PSD cone closure: {psd_ok}")
    print(f"  closed cone: {cone_ok}")
    print(f"  wrote {args.json_out}")


if __name__ == "__main__":
    main()
