#!/usr/bin/env python3
r"""Finite diagnostic for the differential closure of the moving trace.

The closed trace condition is

    Lambda_s(f) = sum_{k=0}^8 e_k(s) f^(k)(s)/k! = 0.

If it holds for every active s, then all total derivatives vanish:

    D_s^q Lambda_s(f) = 0.

This script samples the endpoint-defect row e(s), estimates its s-derivatives
by finite differences, and builds the rows D_s^q Lambda_s on the jet variables

    f(s), f'(s), ..., f^(8+q)(s).

The key structural check is triangularity: the coefficient of f^(8+q) in
D_s^q Lambda_s is e_8(s)/8!, so if e_8 has no zero on the active interval,
the closed trace condition recursively eliminates all higher jets.  Boundary
concomitants that lie in the differential ideal generated by Lambda therefore
vanish on the closed continuum trace space.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / ".pydeps"))

import mpmath as mp  # noqa: E402

from endpoint_defect_family_mp import defect_at, dot  # noqa: E402


def f(x) -> float:
    return float(x)


def fmt(x, digits: int = 8) -> str:
    return mp.nstr(x, digits)


def signed_defect(s, args):
    vals, neg, vec = defect_at(
        s,
        args.jet_order,
        mp.mpf(args.rmax),
        args.order,
        mp.mpf(args.tol),
    )
    if vec[0] > 0:
        vec = [-x for x in vec]
    return vals, neg, vec


def choose_stencil(index: int, total: int, width: int) -> list[int]:
    width = min(width, total)
    left = index - width // 2
    right = left + width
    if left < 0:
        left = 0
        right = width
    if right > total:
        right = total
        left = total - width
    return list(range(left, right))


def finite_diff_weights(xs, index: int, deriv: int, width: int):
    stencil = choose_stencil(index, len(xs), width)
    x0 = xs[index]
    n = len(stencil)
    mat = mp.matrix(n)
    rhs = mp.matrix(n, 1)
    for power in range(n):
        rhs[power] = mp.factorial(deriv) if power == deriv else mp.mpf("0")
        for col, idx in enumerate(stencil):
            mat[power, col] = (xs[idx] - x0) ** power
    sol = mp.lu_solve(mat, rhs)
    return stencil, [sol[i] for i in range(n)]


def coefficient_derivatives(xs, vecs, index: int, max_q: int, width: int):
    out = []
    for deriv in range(max_q + 1):
        stencil, weights = finite_diff_weights(xs, index, deriv, width)
        row = []
        for k in range(len(vecs[0])):
            row.append(mp.fsum(weights[j] * vecs[stencil[j]][k] for j in range(len(stencil))))
        out.append(row)
    return out


def trace_derivative_row(e_derivs, q: int, jet_order: int):
    """Return row for D_s^q Lambda_s on jets f^(0)..f^(jet_order+q-1)."""
    cols = jet_order + q
    row = [mp.mpf("0") for _ in range(cols)]
    for k in range(jet_order):
        for m in range(q + 1):
            col = k + m
            row[col] += (
                mp.binomial(q, m)
                * e_derivs[q - m][k]
                / mp.factorial(k)
            )
    return row


def row_rank(rows, tol):
    cols = max(len(row) for row in rows)
    mat = mp.matrix(len(rows), cols)
    for i, row in enumerate(rows):
        for j, value in enumerate(row):
            mat[i, j] = value
    gram = mat * mat.T
    vals = mp.eigsy((gram + gram.T) / 2, eigvals_only=True)
    scale = max([abs(v) for v in vals] + [mp.mpf("1")])
    threshold = mp.mpf(tol) * scale
    return sum(1 for v in vals if v > threshold), vals


def closure_coefficients(row, pivot_col: int):
    pivot = row[pivot_col]
    return [-row[j] / pivot for j in range(pivot_col)]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--s-min", default="0.02")
    parser.add_argument("--s-max", default="0.545")
    parser.add_argument("--samples", type=int, default=17)
    parser.add_argument("--dps", type=int, default=70)
    parser.add_argument("--jet-order", type=int, default=9)
    parser.add_argument("--max-q", type=int, default=4)
    parser.add_argument("--stencil-width", type=int, default=9)
    parser.add_argument("--order", type=int, default=55)
    parser.add_argument("--rmax", default="12")
    parser.add_argument("--tol", default="1e-20")
    parser.add_argument("--rank-tol", default="1e-24")
    parser.add_argument("--json-out", default="lambda_differential_closure.json")
    args = parser.parse_args()

    mp.mp.dps = args.dps
    s_min = mp.mpf(args.s_min)
    s_max = mp.mpf(args.s_max)
    if args.samples < args.max_q + 3:
        raise SystemExit("--samples must be larger than --max-q + 2")
    if args.stencil_width <= args.max_q:
        raise SystemExit("--stencil-width must exceed --max-q")

    h = (s_max - s_min) / (args.samples - 1)
    centers = [s_min + i * h for i in range(args.samples)]

    vecs = []
    min_gap = mp.inf
    one_dimensional = True
    prev = None
    min_cos = mp.mpf("1")
    for s in centers:
        vals, neg, vec = signed_defect(s, args)
        if prev is not None and dot(prev, vec) < 0:
            vec = [-x for x in vec]
        if prev is not None:
            min_cos = min(min_cos, abs(dot(prev, vec)))
        prev = vec
        vecs.append(vec)
        one_dimensional = one_dimensional and len(neg) == 1
        min_gap = min(min_gap, vals[1] - vals[0])

    pivot = args.jet_order - 1
    rows = []
    min_abs_pivot = mp.inf
    max_closure_norm_by_q = [mp.mpf("0") for _ in range(args.max_q + 1)]
    max_closure_maxabs_by_q = [mp.mpf("0") for _ in range(args.max_q + 1)]
    min_rank = args.max_q + 1
    min_rank_at = None

    for idx, s in enumerate(centers):
        e_derivs = coefficient_derivatives(
            centers, vecs, idx, args.max_q, args.stencil_width
        )
        trace_rows = [
            trace_derivative_row(e_derivs, q, args.jet_order)
            for q in range(args.max_q + 1)
        ]
        rank, eigs = row_rank(trace_rows, args.rank_tol)
        if rank < min_rank:
            min_rank = rank
            min_rank_at = s
        pivot_abs = abs(vecs[idx][pivot])
        min_abs_pivot = min(min_abs_pivot, pivot_abs)

        closure_rows = []
        for q, row in enumerate(trace_rows):
            pivot_col = pivot + q
            coeffs = closure_coefficients(row, pivot_col)
            norm = mp.sqrt(mp.fsum(c * c for c in coeffs))
            maxabs = max(abs(c) for c in coeffs) if coeffs else mp.mpf("0")
            max_closure_norm_by_q[q] = max(max_closure_norm_by_q[q], norm)
            max_closure_maxabs_by_q[q] = max(max_closure_maxabs_by_q[q], maxabs)
            closure_rows.append(
                {
                    "q": q,
                    "pivotColumn": pivot_col,
                    "pivotCoeff": f(row[pivot_col]),
                    "closureNorm": f(norm),
                    "closureMaxAbs": f(maxabs),
                }
            )

        if idx in (0, len(centers) // 2, len(centers) - 1):
            rows.append(
                {
                    "s": f(s),
                    "rank": rank,
                    "minGramEigenvalue": f(eigs[0]),
                    "pivotE8": f(vecs[idx][pivot]),
                    "closure": closure_rows,
                }
            )

    data = {
        "sMin": f(s_min),
        "sMax": f(s_max),
        "samples": args.samples,
        "h": f(h),
        "jetOrder": args.jet_order,
        "maxQ": args.max_q,
        "stencilWidth": args.stencil_width,
        "oneDimensional": one_dimensional,
        "minGap": f(min_gap),
        "minConsecutiveCos": f(min_cos),
        "pivotIndex": pivot,
        "minAbsPivot": f(min_abs_pivot),
        "expectedRank": args.max_q + 1,
        "minRank": min_rank,
        "minRankAt": f(min_rank_at) if min_rank_at is not None else None,
        "maxClosureNormByQ": [f(x) for x in max_closure_norm_by_q],
        "maxClosureMaxAbsByQ": [f(x) for x in max_closure_maxabs_by_q],
        "sampleRows": rows,
    }
    Path(args.json_out).write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")

    print(
        f"Lambda differential closure s=[{s_min},{s_max}] samples={args.samples} "
        f"max_q={args.max_q} stencil={args.stencil_width}",
        flush=True,
    )
    print(f"  one_dimensional={one_dimensional}", flush=True)
    print(f"  min_gap={fmt(min_gap, 12)} min_consecutive_cos={fmt(min_cos, 12)}", flush=True)
    print(
        f"  pivot e_{pivot}: min_abs={fmt(min_abs_pivot, 12)} "
        f"expected_rank={args.max_q + 1} min_rank={min_rank}",
        flush=True,
    )
    print("  max closure coefficient norms:")
    for q, (norm, maxabs) in enumerate(zip(max_closure_norm_by_q, max_closure_maxabs_by_q)):
        print(f"    q={q}: l2={fmt(norm, 10)} max_abs={fmt(maxabs, 10)}", flush=True)
    print(f"  wrote {args.json_out}", flush=True)


if __name__ == "__main__":
    main()
