#!/usr/bin/env python3
r"""Test the variable-coefficient trace Green concomitant.

The previous scalar test used the wrong differential expression, namely raw
``D_s^Q`` applied to ``h_u(s)=K_B(s,u)``.  The moving closed trace is instead

    P f = Lambda_s(f) = sum_{k=0}^8 e_k(s) f^(k)(s)/k!.

If we commute this trace operator through the scalar source, Green's formula
for the variable-coefficient differential expression gives the boundary row

    B_P[h](f)
      = sum_{k=1}^8 sum_{j=0}^{k-1}
          (-1)^(k-1-j) D_s^(k-1-j)(a_k h)(s0) f^(j)(s0),
        a_k=e_k/k!.

This script computes that row for ``h(s)=K_endpoint,B(s,u)`` and tests whether
it lies in the differential ideal generated by the closed trace,

    span{D_s^q Lambda_s : 0 <= q <= qmax}.

This is still a scalarized diagnostic: it tests the Green concomitant of the
trace differential expression itself.  If this row fails, the remaining
concomitant must use the lower-level Sturm feature pair before forming the
scalar kernel.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / ".pydeps"))

import mpmath as mp  # noqa: E402

from lambda_differential_closure import (  # noqa: E402
    coefficient_derivatives,
    trace_derivative_row,
)
from endpoint_defect_family_mp import defect_at, dot  # noqa: E402
from quotient_factorization_mp import endpoint_b_quadrature  # noqa: E402
from source_concomitant_membership import (  # noqa: E402
    closest_center_index,
    sample_trace_field,
    solve_membership,
    source_derivatives,
)


def f(x) -> float:
    return float(x)


def fmt(x, digits: int = 8) -> str:
    return mp.nstr(x, digits)


def signed_defect(s, args):
    vals, neg, vec = defect_at(
        s,
        args.jet_order,
        mp.mpf(args.defect_rmax),
        args.defect_order,
        mp.mpf(args.tol),
    )
    if vec[0] > 0:
        vec = [-x for x in vec]
    return vals, neg, vec


def local_trace_field(args, s0):
    if args.local_points % 2 != 1:
        raise SystemExit("--local-points must be odd")
    half = args.local_points // 2
    step = mp.mpf(args.local_step)
    centers = [s0 + (i - half) * step for i in range(args.local_points)]
    if centers[0] < mp.mpf(args.s_min) or centers[-1] > mp.mpf(args.s_max):
        raise SystemExit("local stencil leaves [s-min,s-max]")

    vecs = []
    prev = None
    min_gap = mp.inf
    min_cos = mp.mpf("1")
    for s in centers:
        vals, _neg, vec = signed_defect(s, args)
        if prev is not None and dot(prev, vec) < 0:
            vec = [-x for x in vec]
        if prev is not None:
            min_cos = min(min_cos, abs(dot(prev, vec)))
        prev = vec
        vecs.append(vec)
        min_gap = min(min_gap, vals[1] - vals[0])
    return centers, vecs, min_gap, min_cos, half


def product_derivative(e_derivs, h_derivs, k: int, n: int):
    """D^n[(e_k/k!) h] at the base point."""
    return mp.fsum(
        mp.binomial(n, m) * e_derivs[m][k] * h_derivs[n - m] / mp.factorial(k)
        for m in range(n + 1)
    )


def trace_green_concomitant_row(e_derivs, h_derivs, jet_order: int):
    """Return the Lagrange boundary row for P=sum e_k D^k/k!."""
    # Lambda has coefficients k=0..jet_order-1 and order jet_order-1.
    order = jet_order - 1
    row = [mp.mpf("0") for _ in range(order)]
    for k in range(1, jet_order):
        for j in range(k):
            n = k - 1 - j
            row[j] += ((-1) ** n) * product_derivative(e_derivs, h_derivs, k, n)
    return row


def pad_row(row, cols):
    return row + [mp.mpf("0") for _ in range(cols - len(row))]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--s-min", default="0.02")
    parser.add_argument("--s-max", default="0.545")
    parser.add_argument("--samples", type=int, default=17)
    parser.add_argument("--s0", default="0.2825")
    parser.add_argument("--t-values", default="0.08 0.24 0.40 0.52")
    parser.add_argument("--max-trace-q", type=int, default=6)
    parser.add_argument("--dps", type=int, default=70)
    parser.add_argument("--jet-order", type=int, default=9)
    parser.add_argument("--stencil-width", type=int, default=9)
    parser.add_argument("--local-step", default="0")
    parser.add_argument("--local-points", type=int, default=17)
    parser.add_argument("--defect-order", type=int, default=55)
    parser.add_argument("--defect-rmax", default="12")
    parser.add_argument("--kernel-order", type=int, default=50)
    parser.add_argument("--kernel-rmax", default="14")
    parser.add_argument("--tol", default="1e-20")
    parser.add_argument("--json-out", default="trace_concomitant_membership.json")
    args = parser.parse_args()

    mp.mp.dps = args.dps
    c = mp.pi
    s0 = mp.mpf(args.s0)
    t_values = [mp.mpf(piece) for piece in args.t_values.replace(",", " ").split()]
    order = args.jet_order - 1
    max_coeff_deriv = max(args.max_trace_q, order - 1)
    active_width = args.local_points if mp.mpf(args.local_step) > 0 else args.stencil_width
    if active_width <= max_coeff_deriv:
        raise SystemExit("active stencil width must exceed the highest derivative order")

    if mp.mpf(args.local_step) > 0:
        centers, vecs, min_gap, min_cos, idx = local_trace_field(args, s0)
    else:
        centers, vecs, min_gap, min_cos = sample_trace_field(args)
        idx = closest_center_index(centers, s0)
    actual_s0 = centers[idx]
    e_derivs = coefficient_derivatives(
        centers, vecs, idx, max_coeff_deriv, active_width
    )
    trace_rows = [
        trace_derivative_row(e_derivs, q, args.jet_order)
        for q in range(args.max_trace_q + 1)
    ]

    r_nodes, r_weights = endpoint_b_quadrature(mp.mpf(args.kernel_rmax), args.kernel_order)
    rows = []

    print(
        f"Trace Green concomitant membership s0={s0} nearest={actual_s0} "
        f"max_trace_q={args.max_trace_q}",
        flush=True,
    )
    print(f"  trace min_gap={fmt(min_gap, 12)} min_cos={fmt(min_cos, 12)}", flush=True)
    print("  t      qmax  generators  rel_residual  alpha_norm  target_norm", flush=True)

    for t in t_values:
        h_derivs = source_derivatives(c, actual_s0, t, order - 1, r_nodes, r_weights)
        target = trace_green_concomitant_row(e_derivs, h_derivs, args.jet_order)
        for qmax in range(args.max_trace_q + 1):
            generators = trace_rows[: qmax + 1]
            cols = max(len(target), max(len(row) for row in generators))
            alpha, res_norm, target_norm, rel = solve_membership(
                pad_row(target, cols),
                [pad_row(row, cols) for row in generators],
            )
            alpha_norm = mp.sqrt(mp.fsum(a * a for a in alpha)) if alpha else mp.mpf("0")
            rows.append(
                {
                    "t": f(t),
                    "maxTraceQ": qmax,
                    "generators": len(generators),
                    "relativeResidual": f(rel),
                    "residualNorm": f(res_norm),
                    "targetNorm": f(target_norm),
                    "alphaNorm": f(alpha_norm),
                    "alphaMaxAbs": f(max(abs(a) for a in alpha)) if alpha else 0.0,
                }
            )
            print(
                f"  {fmt(t, 6):>6} {qmax:5d} {len(generators):10d} "
                f"{fmt(rel, 8):>12} {fmt(alpha_norm, 8):>11} {fmt(target_norm, 8):>11}",
                flush=True,
            )

    data = {
        "sMin": f(mp.mpf(args.s_min)),
        "sMax": f(mp.mpf(args.s_max)),
        "requestedS0": f(s0),
        "actualS0": f(actual_s0),
        "samples": args.samples,
        "jetOrder": args.jet_order,
        "stencilWidth": args.stencil_width,
        "localStep": f(mp.mpf(args.local_step)),
        "localPoints": args.local_points if mp.mpf(args.local_step) > 0 else 0,
        "maxTraceQ": args.max_trace_q,
        "tValues": [f(t) for t in t_values],
        "traceMinGap": f(min_gap),
        "traceMinConsecutiveCos": f(min_cos),
        "rows": rows,
    }
    Path(args.json_out).write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"  wrote {args.json_out}", flush=True)


if __name__ == "__main__":
    main()
